name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Ruff lint & format
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: check
      - uses: astral-sh/ruff-action@v3
        with:
          args: format --check

  validate-hassfest:
    runs-on: ubuntu-latest
    name: Validate with hassfest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master

  validate-hacs:
    runs-on: ubuntu-latest
    name: Validate with HACS
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:
          category: integration
